POST http://localhost:3003/users/signup
Content-Type: application/json

{
"name":"Julia", 
"email":"juju@lab.com",
"password":"abacate",
"role":"ADMIN"
}

###

POST http://localhost:3003/users/signup
Content-Type: application/json

{
"name":"Thor", 
"email":"thor@lab.com",
"password":"thor123",
"role":"ADMIN"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
"email":"juju@lab.com",
"password":"abacate"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
"email":"thor@lab.com",
"password":"thor123"
}

###

POST http://localhost:3003/band/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDYxZGYwLTg4NzgtNDJiZC1iNjUwLTAwNTgwYjI4NWE4YyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MzQwMzUwNCwiZXhwIjoxNjUzNDA0OTQ0fQ.72zHXFGWshhfN86vrgKMAdcABJPp13ou66bDAnZurrc

{
"name": "juju e os abacates",
"music_genre": "Rap",
"responsible": "Vovó Juju"
}

###

GET http://localhost:3003/band/juju e os abacates
Content-Type: application/json

###

POST http://localhost:3003/show/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwMDYxZGYwLTg4NzgtNDJiZC1iNjUwLTAwNTgwYjI4NWE4YyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MzQwMzUwNCwiZXhwIjoxNjUzNDA0OTQ0fQ.72zHXFGWshhfN86vrgKMAdcABJPp13ou66bDAnZurrc

{
"week_day": "SEXTA",
"start_time": 16,
"end_time": 19,
"band_id": "8850804d-695a-491d-b147-fb982f9c403f"
}

###

GET http://localhost:3003/show/SEXTA
Content-Type: application/json