POST http://localhost:3003/users/signup
Content-Type: application/json

{
"name":"Olivia", 
"email":"pimpa@lab.com",
"password":"pimpa123",
"role":"NORMAL"
}

###

POST http://localhost:3003/users/signup
Content-Type: application/json

{
"name":"Thor", 
"email":"thor@lab.com",
"password":"thor123",
"role":"ADMIN"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
"email":"pimpa@lab.com",
"password":"pimpa123"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
"email":"thor@lab.com",
"password":"thor123"
}

###

POST http://localhost:3003/band/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkYmUzM2VkLTBjMzItNGVlOS1hMThmLTgzYjM2ODk4MzZmNSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MjU3ODgzMSwiZXhwIjoxNjUyNTgwMjcxfQ.H9L-VeIHazMx4r6nTX4P7dbDv23gij8FFzWT7T7y94E

{
"name": "Oliviaa",
"music_genre": "Pisadinha",
"responsible": "Pimpinha"
}

###

GET http://localhost:3003/band/Oliviaa
Content-Type: application/json

###

POST http://localhost:3003/show/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkYmUzM2VkLTBjMzItNGVlOS1hMThmLTgzYjM2ODk4MzZmNSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MjY2NDE1NSwiZXhwIjoxNjUyNjY1NTk1fQ.JcVSDrXCIsH2uiynydjBPM_B_XCXSjQz8te3qyJHfe4

{
"week_day": "SEXTA",
"start_time": 16,
"end_time": 19,
"band_id": "31273589-5ad0-4a52-bfad-adeddaa53445"
}

###

GET http://localhost:3003/show/SEXTA
Content-Type: application/json